### ISSUE TITLE
Social Auth with Gmail SSO Causing Error --> 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by poovarasudev** [python-social-auth/social-app-django#488]
After implementing SSO with google in Django application, facing this error.

Environment:

Request Method: GET
Request URL: http://localhost:8000/social-auth/complete/google-oauth2/?state=d0eF6OTec9H9i2zapuqAIzIfQt68u2Y8&code=4%2F0Adeu5BWyKAUMtmW-A8pJHPt5CvjnSbL4H4l6HxtQeUHm_Uqcfbm5-kqP-mcxFnlCT_8SVw&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=4&prompt=consent

Django Version: 4.2.4
Python Version: 3.10.12
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'django_celery_results',
 'social_django',
 'core',
 'accounts',
 'silk',
 'debug_toolbar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'core.middlewares.timezone_middleware.TimezoneMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'silk.middleware.SilkyMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Traceback (most recent call last):
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_django/utils.py", line 46, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_django/views.py", line 30, in complete
    return do_complete(
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_core/actions.py", line 43, in do_complete
    partial = partial_pipeline_data(backend, user, *args, **kwargs)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_core/utils.py", line 186, in partial_pipeline_data
    partial = backend.strategy.partial_load(partial_token)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_core/strategy.py", line 92, in partial_load
    return partial_load(self, token)
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_core/pipeline/utils.py", line 59, in partial_load
    args = partial.args
  File "/Users/poovarasu/opt/anaconda3/envs/linkedin_app/lib/python3.10/site-packages/social_core/storage.py", line 298, in args
    return self.data.get("args", [])

Exception Type: AttributeError at /social-auth/complete/google-oauth2/
Exception Value: 'str' object has no attribute 'get'

![Screenshot 2023-08-24 at 8 55 39 PM](https://github.com/python-social-auth/social-app-django/assets/45655443/173a8c43-4206-4070-958e-2cfcc3291ad7)

**Comment by wloggains** [comment]
This issue started popping up for me as well after I upgraded Django from 4.2.1 to 4.2.2.

**Comment by poovarasudev** [comment]
I found this issue, it is due to scope in google developer account
